// <auto-generated />
namespace RecursionHome.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class policeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(policeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202507060514292_policeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
