// <auto-generated />
namespace HomeworkCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class featMSGBoardHomework2Posts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(featMSGBoardHomework2Posts));
        
        string IMigrationMetadata.Id
        {
            get { return "202503090254238_feat-MSGBoardHomework2-Posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
