// <auto-generated />
namespace HomeworkCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class featProductsProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(featProductsProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202503090518552_feat-Products-Products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
