// <auto-generated />
namespace HomeworkCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class featProductsCategoriesAndSubCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(featProductsCategoriesAndSubCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "202503090445484_feat-Products-CategoriesAndSubCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
