// <auto-generated />
namespace HomeworkCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class featAdAdImgs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(featAdAdImgs));
        
        string IMigrationMetadata.Id
        {
            get { return "202503090403352_feat-Ad-AdImgs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
