// <auto-generated />
namespace HomeworkCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class featProductsProductsImgs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(featProductsProductsImgs));
        
        string IMigrationMetadata.Id
        {
            get { return "202503090555464_feat-Products-ProductsImgs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
