// <auto-generated />
namespace HomeworkCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updateMSGBoardHomework2stopforeignkeyconnect : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateMSGBoardHomework2stopforeignkeyconnect));
        
        string IMigrationMetadata.Id
        {
            get { return "202503090229440_update-MSGBoardHomework2-stopforeignkeyconnect"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
