// <auto-generated />
namespace HomeworkCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class featMsgBoardHomework1UserAndBoard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(featMsgBoardHomework1UserAndBoard));
        
        string IMigrationMetadata.Id
        {
            get { return "202503081531497_feat-MsgBoardHomework1-UserAndBoard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
